obstacle_range: 2.5
raytrace_range: 10.0
footprint: [[0.30, 0.25], [0.30, -0.25], [-0.50, -0.25], [-0.50, 0.25]]
#robot_radius: ir_of_robot
inflation_radius: 1.0 #1.0
cost_scaling_factor: 0.5 #10
observation_sources: base_scan
base_scan: {
  sensor_frame: lrf_link, 
  topic: front/scan, #/base_scan,
  data_type: LaserScan, 
  expected_update_rate: 1.0,
  observation_persistence: 0.0, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 1.0, 
  min_obstacle_height: -0.15
  }  

transform_tolerance: 1.5
  
