local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.20
transform_tolerance: 1.5
